name: Publish to GitHub Packages

on:
  push:
    tags:
      - "v*"

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: temurin

      - name: Build and Deploy
        run: mvn clean deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}



#               ----- release way -----
#  git add .
#  git commit -m "release 1.0.0"
#  git tag v1.0.0
#  git push origin main
#  git push origin v1.0.0